language: java
sudo: false  
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk6
branches:
    except:    
        - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
install:
    - true
script:
    - mvn verify
